server:
  port: 8080


mybatis:
  type-aliases-package: com.zhang.entity
  config-location: classpath:mapper/config/sqlMapConfig.xml
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
